import express from "express";
const app = express();
import morgan from "morgan";

import productRoutes from "./api/routes/products.js"
import orderRoutes from "./api/routes/orders.js"

app.use(morgan('dev'))

app.use("/products", productRoutes);
app.use("/orders", orderRoutes);


// to handle any other undefined route
app.use("*", (req, res, next) => {
    res.status(404).json({
        Error: "there was an error"
    })
})


// to handle any error generated by our server
app.use((error, req, res, next) => {
    res.status(error.status || 500).json({
        error: {
            message: error.message
        }
    })
})


export default app;