import express from "express";
const app = express();
import morgan from "morgan";

import productRoutes from "./api/routes/products.js"
import orderRoutes from "./api/routes/orders.js"

// Middlewares
app.use(morgan('dev'))
app.use(express.json())

// CORS Error handling
app.use((req, res, next) => {
    res.header('Access-Control-Allow-Origin', "*")
    res.header( "Access-Control-Allow-Headers", 
                "Origin, X-Requested-With, Content-Type, Accept, Authorization")

    if(req.method === 'OPTIONS'){
        res.header("Access-Control-Allow-Origin", "POST, PUT, DELETE, POST, GET")
        return res.status(200).json({})
    }
    next(); 
})

// routes
app.use("/products", productRoutes);
app.use("/orders", orderRoutes);


// to handle any other undefined route
app.use("*", (req, res, next) => {
    res.status(404).json({
        Error: "there was an error"
    })
})


// to handle any error generated by our server
app.use((error, req, res, next) => {
    res.status(error.status || 500).json({
        error: {
            message: error.message
        }
    })
})


export default app;